---
# PLUGINS
# ==========================================

# Startup
# -------
- repo: Shougo/dein.vim
- repo: rafi/awesome-vim-colorschemes
- repo: rafi/vim-badge

- repo: embear/vim-localvimrc
  hook_source: |
    let g:localvimrc_enable = 1
    let g:localvimrc_name = ".vproject"

- repo: christoomey/vim-tmux-navigator
- repo: junegunn/vim-peekaboo
- repo: tpope/vim-sleuth
- repo: itchyny/vim-gitbranch
- repo: itchyny/vim-parenmatch
- repo: itchyny/vim-cursorword
  hook_add: |
    autocmd MyAutoCmd FileType denite,qf,nerdtree let b:cursorword=0
    autocmd MyAutoCmd InsertEnter * let b:cursorword=0
    autocmd MyAutoCmd InsertLeave * let b:cursorword=1

# Lazy Loading
# ==========================================

# Languages
# ---------

- repo: plasticboy/vim-markdown
  on_ft: markdown
  hook_add: |
    let g:vim_markdown_override_foldtext = 0
    let g:vim_markdown_initial_foldlevel = 999
    let g:vim_markdown_new_list_item_indent = 2
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_fenced_languages = [
      \ 'c++=cpp',
      \ 'viml=vim',
      \ 'bash=sh',
      \ 'ini=dosini'
      \ ]

- repo: rhysd/vim-gfm-syntax
  depends: vim-markdown
  on_ft: markdown
  hook_source: |
    let g:gfm_syntax_enable_always = 0
    let g:gfm_syntax_highlight_emoji = 0
    let g:gfm_syntax_enable_filetypes = ['markdown']

# ==========================================
# Interface
# ---------

- repo: vimwiki/vimwiki
  if: empty($VIM_MINIMAL)
  on_map: { n: <Plug> }
  on_cmd: Vimwiki
  hook_add: |
    let g:vimwiki_use_calendar = 1
    let g:vimwiki_hl_headers = 1
    let g:vimwiki_hl_cb_checked = 1
    let g:vimwiki_autowriteall = 0
  hook_source: |
    let g:vimwiki_list = [
    \   { 'diary_header': 'Daily',
    \     'diary_link_fmt': '%Y-%m/%d',
    \     'auto_toc': 1,
    \     'path': '~/docs/orion/',
    \     'syntax': 'markdown',
    \     'ext': '.md' },
    \   { 'path': '~/docs/wiki/',
    \     'syntax': 'markdown',
    \     'ext': '.md' }
    \ ]

# enhances netrw - use NETRW with a split-window rather than a project drawer
- { repo: tpope/vim-vinegar }

- repo: neomake/neomake
  on_cmd: Neomake
  hook_source: source $VIMPATH/config/plugins/neomake.vim
  hook_add: |
    let g:lint_filetypes = [
      \  'ansible', 'python', 'php', 'ruby', 'vim', 'go', 'sh',
      \  'javascript', 'jsx', 'javascript.jsx', 'json', 'css',
      \  'markdown', 'html', 'yaml'
      \ ]
    autocmd MyAutoCmd BufWritePost *
      \ if index(g:lint_filetypes, &filetype) > -1 && empty(&buftype)
      \|   Neomake
      \| elseif &filetype =~ 'html'
      \|   Neomake tidy
      \| endif


# ==========================================
# CTRLP.vim
# --------
- repo: ctrlpvim/ctrlp.vim
  on_cmd: CtrlP
  hook_source: source $VIMPATH/config/plugins/ctrlp.vim


# ==========================================
# Commands
# --------

- repo: scrooloose/nerdtree
  on_map: { n: <Plug> }
  hook_post_source: source $VIMPATH/config/plugins/nerdtree.vim

- { repo: tpope/vim-commentary, on_map: <Plug>Commentary }
- repo: tpope/vim-unimpaired

- repo: majutsushi/tagbar
  if: empty($VIM_MINIMAL)
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_sort = 0
    let g:tagbar_autofocus = 1
    let g:tagbar_width = 40
    let g:tagbar_autoclose = 0

- repo: junegunn/fzf.vim
  hook_source: |
    set rtp+=/usr/bin/fzf

- repo: mileszs/ack.vim
  if: executable('ag') && empty($VIM_MINIMAL)
  hook_source: |
    let g:ag_working_path_mode='r'
    if executable('ag')
      let g:ackprg = 'ag --vimgrep'
    endif

# ==========================================
# Completion
# ----------
- repo: ludovicchabant/vim-gutentags
  if: executable('ctags') && empty($VIM_MINIMAL)
  on_path: .*
  hook_add: |
    let g:gutentags_cache_dir = $VARPATH.'/tags'
    let g:gutentags_generate_on_write = 1
    let g:gutentags_generate_on_missing = 0
    let g:gutentags_generate_on_new = 0
    let g:gutentags_ctags_exclude_wildignore = 1
    let g:gutentags_ctags_exclude = [
      \ '*/wp-admin', '*/wp-content', '*/wp-includes',
      \ '*/application/vendor', '*/vendor/ckeditor', '*/media/vendor',
      \ '*/venv']

- { repo: roxma/nvim-yarp }
- { repo: roxma/vim-hug-neovim-rpc }

- repo: Shougo/deoplete.nvim
  depends: context_filetype.vim
  on_i: 1
  hook_add: let g:deoplete#enable_at_startup = 1
  hook_source: source $VIMPATH/config/plugins/deoplete.vim

- repo: Shougo/neosnippet.vim
  depends: [ neosnippet-snippets, context_filetype.vim ]
  if: empty($VIM_MINIMAL)
  on_event: InsertCharPre
  on_ft: snippet
  hook_add: let g:neosnippet#data_directory = $VARPATH.'/snippets'
  hook_source: |
    let g:neosnippet#enable_snipmate_compatibility = 1
    let g:neosnippet#enable_completed_snippet = 1
    let g:neosnippet#expand_word_boundary = 1
    let g:neosnippet#disable_runtime_snippets = {
      \ 'c': 1,
      \ }
    autocmd MyAutoCmd InsertLeave * NeoSnippetClearMarkers

# - repo: Shougo/echodoc.vim
  # if: empty($VIM_MINIMAL)
  # on_event: CompleteDone
  # hook_post_source: call echodoc#enable()

- repo: Raimondi/delimitMate
  on_i: 1
  hook_source: |
    let g:delimitMate_expand_cr = 1
    let g:delimitMate_excluded_ft = 'html'

- repo: Shougo/neosnippet-snippets
  if: empty($VIM_MINIMAL)

- { repo: Shougo/context_filetype.vim, lazy: 1, if: empty($VIM_MINIMAL) }
# - { repo: Shougo/neco-vim, on_ft: vim, if: empty($VIM_MINIMAL) }
# - { repo: Shougo/neco-syntax, on_source: [ neocomplete.vim, deoplete.nvim ]}

#  vim: set ts=2 sw=2 tw=80 et :
