---
# PLUGINS
# ==========================================

# Startup
# -------
- repo: Shougo/dein.vim
- repo: rafi/awesome-vim-colorschemes
- repo: rafi/vim-badge

- repo: embear/vim-localvimrc
  hook_source: |
    let g:localvimrc_enable = 1

- repo: christoomey/vim-tmux-navigator
- repo: junegunn/vim-peekaboo
- repo: tpope/vim-sleuth
- repo: itchyny/vim-gitbranch
- repo: itchyny/vim-parenmatch
- repo: itchyny/vim-cursorword
  hook_add: |
    autocmd MyAutoCmd FileType denite,qf,nerdtree let b:cursorword=0
    autocmd MyAutoCmd InsertEnter * let b:cursorword=0
    autocmd MyAutoCmd InsertLeave * let b:cursorword=1

# ==========================================
# Completion
# ----------
- repo: ludovicchabant/vim-gutentags
  if: executable('ctags') && empty($VIM_MINIMAL)
  on_path: .*
  hook_add: |
    let g:gutentags_cache_dir = $VARPATH.'/tags'
    let g:gutentags_generate_on_write = 1
    let g:gutentags_generate_on_missing = 0
    let g:gutentags_generate_on_new = 0
    let g:gutentags_ctags_exclude_wildignore = 1
    let g:gutentags_ctags_exclude = [
      \ '*/wp-admin', '*/wp-content', '*/wp-includes',
      \ '*/application/vendor', '*/vendor/ckeditor', '*/media/vendor',
      \ '*/venv']


# ==========================================
# Commands
# --------
- repo: majutsushi/tagbar
  if: empty($VIM_MINIMAL)
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_sort = 0
    let g:tagbar_autofocus = 1
    let g:tagbar_width = 40
    let g:tagbar_autoclose = 0
    if executable('jsctags')
      let g:tagbar_type_javascript = { 'ctagsbin': 'jsctags' }
    endif

#  vim: set ts=2 sw=2 tw=80 et :
